dist: trusty
sudo: required

os:
  - linux

# in theory travis should detect what to install,
# but we use meson, which is not supported by travis yet and we need custom commands
compiler:
  - gcc

language:
  - c

env:
  global:
    DATETIME=$(date +%Y%m%d-%H%M%S)

matrix:
  include:
    - os: linux
      dist: trusty
      env: 
        TARGET=linux-amd64
        EXTENSION=
    - os: linux
      dist: trusty
      env:
        TARGET=linux-armhf
        EXTENSION=
    - os: linux
      dist: trusty
      env:
        TARGET=linux-i686
        EXTENSION=
    - os: linux
      dist: trusty
      env:
        TARGET=windows-x86
        EXTENSION=.exe
    - os: linux
      dist: trusty
      env:
        TARGET=windows-x64
        EXTENSION=.exe

before_install:
  # show some extra info
  - export | sort
  - env | sort
  # update base distro
  - sudo apt-get update
  # install base packages
  - sudo apt-get -y install build-essential python-virtualenv python3-dev python3-pip ninja-build cmake gcc-multilib
  # ensure we do not have curl dev libs, otherwise it caused cross compilations to fail
  - sudo apt-get -y remove libcurl.*-dev
  - sudo apt-get -y remove libpcre*-dev
  # install cross complier if we gonna do binaries for windows
  - if [ -z "${TARGET##*win*}" ]; then sudo apt-get -y install mingw-w64 ; fi
  # install cross compiler tools if we gonna do binares for arm/raspberry
  # notice it will remove gcc-multilib
  - if [ -z "${TARGET##*arm*}" ]; then sudo apt-get -y install gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf ;fi
  # activate virtualenv with python3, meson requires python3
  - virtualenv .venv --python=python3
  - . .venv/bin/activate
  - pip3 install --upgrade pip
  # install python packages like meson, ninja etc...
  - pip3 install -r requirements.txt

# each script section is executed in matrix build
script:
  - echo TARGET=${TARGET}
  - mkdir build_${TARGET} || true
  - meson build_${TARGET} --cross-file tools/cross-compilation/${TARGET}.txt
  - ninja -v -C build_${TARGET}
  # print basic info about compiled files
  - file build_${TARGET}/mvdsv${EXTENSION}
  - mkdir -p uploads_to_gcs
  - mv build_${TARGET}/mvdsv${EXTENSION} uploads_to_gcs/${DATETIME}_${TRAVIS_COMMIT:0:7}_mvdsv${EXTENSION}

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: false
